# Generated by Django 4.0.4 on 2022-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tema', models.CharField(max_length=255)),
                ('cultivo', models.CharField(max_length=255)),
                ('posteador', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
